# Generated by Django 4.2.5 on 2023-09-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('OT', 'Other'), ('EL', 'Electronics'), ('FA', 'Fashion'), ('AR', 'Art')], default='OT', max_length=2),
        ),
    ]
